[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "pizzacap-app"

[[redirects]]
  from = "/api/*"
  to = "https://web-production-f8dcc1.up.railway.app"
  status = 200
