[build]
  command = "npm run build"
  publish = "dist"

And if you want to proxy API requests in dev:

[[redirects]]
  from = "/api/*"
  to = "https://your-flask-api-url.railway.app/api/:splat"
  status = 200